main_app/urls.py
from django.urls import path
from . import views


urlpatterns = [
  path('', views.home, name='home'),
  path('about/', views.about, name='about'),
  path('watches/', views.watches_index, name='index'),
  path('watches/<int:watch_id>/', views.watches_detail, name='detail'),
  # new route used to show a form and create a cat
  path('watches/create/', views.WatchCreate.as_view(), name='watches_create'),
  # Add the new routes below
  path('watches/<int:pk>/update/', views.WatchUpdate.as_view(), name='watches_update'),
  path('watches/<int:pk>/delete/', views.WatchDelete.as_view(), name='watches_delete'),
  path('watches/<int:watch_id>/add_service/', views.add_service, name='add_service'),
  path('straps/', views.StrapList.as_view(), name='straps_index'),
  path('straps/<int:pk>/', views.StrapDetail.as_view(), name='straps_detail'),
  path('straps/create/', views.StrapCreate.as_view(), name='straps_create'),
  path('straps/<int:pk>/update/', views.StrapUpdate.as_view(), name='straps_update'),
  path('straps/<int:pk>/delete/', views.StrapDelete.as_view(), name='straps_delete'),
  path('watches/<int:watch_id>/assoc_strap/<int:strap_id>/', views.assoc_strap, name='assoc_strap'),
  path('accounts/signup/', views.signup, name='signup'),
]

watchcollector/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main_app.urls')),
    # include the built-in auth urls for the built-in views
    path('accounts/', include('django.contrib.auth.urls')),
]

main_app/models.py
from django.db import models
# Import the reverse function
from django.urls import reverse
from datetime import date
# Import the User
from django.contrib.auth.models import User

# A tuple of 2-tuples
PERIOD = (
  ('A', 'Annualy'),
  ('Q', 'Quartely'),
  ('M', 'Monthly')
)
class Strap(models.Model):
  material = models.CharField(max_length=50)
  color = models.CharField(max_length=50)

  def get_absolute_url(self):
      return reverse('straps_detail', kwargs={'pk': self.id})

# Create your models here.
class Watch(models.Model):
  make = models.CharField(max_length=100) 
  model = models.CharField(max_length=100)
  movement = models.CharField(max_length=100)
  description = models.TextField(max_length=300)
  price = models.IntegerField()
  straps = models.ManyToManyField(Strap)
  user = models.ForeignKey(User, on_delete=models.CASCADE)

 # changes to instance methods do not require re-generation / running of migrations
  def __str__(self):
      return self.make

# Add this method
  def get_absolute_url(self):
     return reverse('detail', kwargs={'watch_id': self.id})

class Service(models.Model):
  date = models.DateField('service date')
  period = models.CharField(
    max_length=1,
    # add the 'choices' field option
    choices=PERIOD,
    # set the default value for meal to be 'B'
    default=PERIOD[0][0]
  ) 

  # Create a watch_id FK
  watch = models.ForeignKey(Watch, on_delete=models.CASCADE)

  def __str__(self):
    # Nice method for obtaining the friendly value of a Field.choice
    return f"{self.get_service_display()} on {self.date}"
  # change the default sort
  class Meta:
    ordering = ['-date']  

main_app/forms.py
from django.forms import ModelForm
from .models import Service

class ServiceForm(ModelForm):
  class Meta:
    model = Service
    fields = ['date', 'period']

main_app/views.py
from django.shortcuts import render, redirect
# Add the following import
from django.views.generic import ListView
from django.views.generic.detail import DetailView
from django.contrib.auth import login
# Import the login_required decorator
from django.contrib.auth.decorators import login_required
# Import the mixin for class-based views
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.forms import UserCreationForm
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from .models import Watch, Strap
# import the ServiceForm
from .forms import ServiceForm

# Define the home view
def home(request):
  return render(request, 'home.html')

def about(request):
  return render(request, 'about.html')

# Add new view
def watches_index(request):
  watches = Watch.objects.filter(user=request.user)
  return render(request, 'watches/index.html', { 'watches': watches })

# update this view function
@login_required
def watches_detail(request, watch_id):
  watch = Watch.objects.get(id=watch_id)
  # instantiate FeedingForm to be rendered in the template
  service_form = ServiceForm()

# displaying unassociated straps
  straps_watch_doesnt_have = Strap.objects.exclude(id__in = watch.straps.all().values_list('id'))

  return render(request, 'watches/detail.html', {
    # include the cat and feeding_form in the context
    'watch': watch,
    'service_form': service_form,
    'straps' : straps_watch_doesnt_have,
  })

@login_required
def add_service(request, watch_id):
  # create the ModelForm using the data in request.POST
  form = ServiceForm(request.POST)
  # validate the form
  if form.is_valid():
    new_service = form.save(commit=False)
    new_service.watch_id = watch_id
    new_service.save()
  return redirect('detail', watch_id=watch_id) 
  
@login_required
def assoc_strap(request, watch_id, strap_id,):
  # Note that you can pass a straps id instead of the whole object  
  Watch.objects.get(id=watch_id).straps.add(strap_id)
  return redirect('detail', watch_id=watch_id) 

def signup(request):
  error_message = ''
  if request.method == 'POST':
    # This is how to create a 'user' form object
    # that includes the data from the browser
    form = UserCreationForm(request.POST)
    if form.is_valid():
      # This will add the user to the database
      user = form.save()
      # This is how we log a user in via code
      login(request, user)
      return redirect('index')
    else:
      error_message = 'Invalid sign up - try again'
  # A bad POST or a GET request, so render signup.html with an empty form
  form = UserCreationForm()
  context = {'form': form, 'error_message': error_message}
  return render(request, 'registration/signup.html', context)  

class WatchCreate(CreateView):
  model = Watch
  fields = ['make', 'model', 'movement', 'description', 'price']
  success_url = '/watches/'

  # This inherited method is called when a
  # valid cat form is being submitted
  def form_valid(self, form):
    # Assign the logged in user (self.request.user)
    form.instance.user = self.request.user  # form.instance is the cat
    # Let the CreateView do its job as usual
    return super().form_valid(form)

class WatchUpdate(UpdateView):
  model = Watch 
  # Let's disallow the renaming of a watch by excluding the name field!
  fields = ['model', 'movement', 'description', 'price']

class WatchDelete(DeleteView):
  model = Watch
  success_url = '/watches/'

class StrapCreate(CreateView):
  model = Strap
  fields = ('material', 'color')

class StrapUpdate(UpdateView):
  model = Strap
  fields = ('name', 'color')

class StrapDelete(DeleteView):
  model = Strap
  success_url = '/straps/'  

class StrapDetail(DetailView):
  model = Strap
  template_name = 'straps/detail.html'

class StrapList(ListView):
  model = Strap
  template_name = 'straps/index.html'     

main_app/templates/about.html
{% extends 'base.html' %} {% block content %}

<h1>About the Watch Collector</h1>

<hr/>

<p>Hire the Watch Collector</p>

{% endblock %}
 

main_app/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>The Watch Collector</title>

    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css"
    />

    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>

    <link
      rel="stylesheet"
      type="text/css"
      href="{% static 'css/style.css' %}"
    />
  </head>

  <body>
    <header class="navbar-fixed">
      <nav>
        <div class="nav-wrapper #dce775 lime lighten-2">
          <ul>
            <li>
              <a href="/" class="left brand-logo">&nbsp;&nbsp;WatchCollector</a>
            </li>
          </ul>
          <ul class="right">
            <li><a href="{% url 'about' %}">About</a></li>
            {% if user.is_authenticated %}
            <li><a href="{% url 'straps_create' %}">Add a Strap</a></li>
            <li><a href="{% url 'straps_index' %}">View All My Straps</a></li>
            <li><a href="{% url 'watches_create' %}">Add a Watch</a></li>
            <li><a href="{% url 'index' %}">View All My Watches</a></li>
            <li><a href="{% url 'logout' %}">Log Out</a></li>
            {% else %}
            <li><a href="{% url 'signup' %}">Sign Up</a></li>
            <li><a href="{% url 'login' %}">Log In</a></li>
            {% endif %}
          </ul>
        </div>
      </nav>
    </header>
    <main class="container">{% block content %} {% endblock %}</main>
    <footer class="page-footer #00e676 green accent-3">
      <div class="right">
        All Rights Reserved, &copy; 2022 Watch Collector Inc. &nbsp;
      </div>
    </footer>
  </body>
</html>

main_app/templates/home.html
{% extends 'base.html' %} {% block content %}

<h1>The watch collector</h1>

{% endblock %}

main_app/templates/main_app/strap_confirm_delete.html
{% extends 'base.html' %}

{% block content %}

<h1>Delete Strap</h1>

<h4>
    Are you sure you want to delete <span class="teal-text">{{ object.name }}</span>?
</h4>

<form action="" method="post">
    {% csrf_token %}
    <input class="btn red" type="submit" value="Yes - Delete">
    <a class="btn blue" href="{% url 'detail' object.id %}">Cancel</a>
</form>

{% endblock %}

main_app/templates/main_app/strap_form.html
{% extends 'base.html' %}

{% block content %}

{% if object %}
    <h1>Update {{ object.name }}</h1>
{% else %}
    <h1>Add Strap</h1>
{% endif %}

<form action="" method="post">
    {% csrf_token %}
    <table>
        {{ form.as_table }}
    </table>
    <input class="btn blue" type="submit" value="{% if object %} Update Strap {% else %} Add Strap {% endif %}">
</form>

{% endblock %}

main_app/templates/main_app/watch_confirm_delete.html
{% extends 'base.html' %} {% block content %}
<h1>Delete Watch</h1>

<h4>
  Are you sure you want to delete
  <span class="teal-text">{{ object.name }}</span>?
</h4>

<form action="" method="POST">
  {% csrf_token %}
  <input type="submit" value="Yes - Delete!" class="btn" />
  <a href="{% url 'detail' watch.id %}">Cancel</a>
</form>
{% endblock %}

main_app/templates/main_app/watch_form.html
{% extends 'base.html' %} {% block content %}
<!-- Leaving the action empty makes the form post to the same url used to display it -->
{% if object %}
<h1>Edit <span class="teal-text">{{object.name}}</span></h1>
{% else %}
<h1>Add Watch</h1>
{% endif %}

<form action="" method="post">
  <!-- Django requires the following for security purposes -->
  {% csrf_token %}
  <table>
    <!-- Render the inputs inside of <tr>s & <td>s -->
    {{ form.as_table }}
  </table>
  <input type="submit" value="Submit!" class="btn" />
</form>
{% endblock %}

main_app/templates/straps/detail.html
{% extends 'base.html' %}

{% block content %}

<h1>Strap Details</h1>


<div class="card">
    <a href="{% url 'straps_detail' strap.id %}">
        <div class="card-content">
            <span class="card-title"> <span class="{{ strap.color.lower }}-text">{{ strap.color }}</span> {{ strap.name }}</span>
        </div>
        <div class="card-action">
            <a href="{% url 'straps_update' strap.id %}">Edit</a>
            <a href="{% url 'straps_delete' strap.id %}">Delete</a>
        </div>
    </a>
</div>

{% endblock %}

main_app/templates/straps/index.html
{% extends 'base.html' %}

{% block content %}

<h1>Straps List</h1>
{% for strap in object_list %}
<div class="card">
    <a href="{% url 'straps_detail' strap.id %}">
        <div class="card-content">
            <span class="card-title"> <span class="{{ strap.color }}-text"></span> {{ strap.material }}</span>
        </div>
    </a>
</div>
{% endfor %}


{% endblock %}

main_app/templates/watches/detail.html
{% extends 'base.html' %} {% block content %}

<h1>Watch Details</h1>

<div class="row">
  <div class="col s6">
    <div class="card">
      <div class="card-content">
        <span class="card-title">{{ watch.name }}</span>
        <p>Make: {{ watch.make }}</p>
        <p>Model: {{ watch.model }}</p>
        <p>Movement: {{ watch.movement }}</p>
        <p>Description: {{ watch.description }}</p>
        {% if watch.price > 0 %}
        <p>Price: {{ watch.price }}</p>
        {% else %}
        <p>Price: Not Available</p>
        {% endif %}
      </div>
      <div class="card-action">
        <a href="{% url 'watches_update' watch.id %}">Edit</a>
        <a href="{% url 'watches_delete' watch.id %}">Delete</a>
      </div>
    </div>
  </div>
  <div class="col s6">
  <!-- displayin a form at the top of service column to render the ModelForm's input with the <form> tags -->
    <!--we need to include  -->
  <form action="{% url 'add_service' watch.id %}" method="post">
    {% csrf_token %} {{ service_form.as_p }}
    <input type="submit" class="btn" value="Add Service" />
  </form>
 
    <table class="striped">
      <thead>
        <tr>
          <th>Name</th>
          <th>Period</th>
        </tr>
      </thead>
      <tbody>
        {% for service in watch.service_set.all %}
        <tr>
          <td>{{service.date}}</td>
          <td>{{service.get_period_display}}</td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
</div>
<!-- make the <input>for Feeding Date a sweet date-picker using Materialize. 
  Using Materialize, it takes two steps to get the inputs the way we want them:
1. Select the element(s)
2. "Initialize" the element(s) using Materialize's library-->
<script>
  var dateEl = document.getElementById('id_date');
  M.Datepicker.init(dateEl, {
    format: 'yyyy-mm-dd',
    defaultDate: new Date(),
    setDefaultDate: true,
    autoClose: true
  });

  // add additional JS to initialize select below
  var selectEl = document.getElementById('id_period');
  M.FormSelect.init(selectEl);

</script>

{% endblock %}

main_app/templates/watches/index.html
{% extends 'base.html' %} {% block content %}

<h1>Watches List</h1>

{% for watch in watches %}
<div class="card">
  <div class="card-content">
    <span class="card-title">{{ watch.name }}</span>
    <p>Make: {{ watch.make }}</p>
    <p>Model: {{ watch.model }}</p>
    <p>Movement: {{ watch.movement }}</p>
    <p>Description: {{ watch.description }}</p>
    {% if watch.price > 0 %}
    <p>Price: {{ watch.price }}</p>
    {% else %}
    <p>Price: Not Available</p>
    {% endif %}
  </div>
</div>
{% endfor %} {% endblock %}